apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mlhein/testtest.git
    targetRevision: HEAD
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  sources:
    repoURL: https://github.com/mlhein/testtest.git
    targetRevision: HEAD
    path: guestbook
  destinations:
    server: https://kubernetes.default.svc
    namespace: guestbook